# Generated by Django 5.2.1 on 2025-06-21 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_add_approval_system'),
        ('jobs', '0004_applicationnote_jobalert_jobbookmark_jobshare_and_more'),
    ]

    operations = [
    ]
