# Generated by Django 5.2.1 on 2025-06-18 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision_requested', 'Revision Requested')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='startup',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='startupbookmark',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='startupfounder',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='startuplike',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='startuprating',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='startuptag',
            options={'ordering': ['tag']},
        ),
        migrations.AddField(
            model_name='startup',
            name='cover_image_url',
            field=models.URLField(blank=True, help_text='URL to cover image', null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Whether startup is approved for public listing'),
        ),
        migrations.AddField(
            model_name='startup',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_startups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='startupbookmark',
            name='notes',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='startupcomment',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='startupcomment',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='startupfounder',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='startupfounder',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='startupcomment',
            name='text',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='startupfounder',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddIndex(
            model_name='startup',
            index=models.Index(fields=['is_approved', 'is_featured'], name='startups_st_is_appr_80fd95_idx'),
        ),
        migrations.AddIndex(
            model_name='startup',
            index=models.Index(fields=['industry', 'is_approved'], name='startups_st_industr_7f011e_idx'),
        ),
        migrations.AddIndex(
            model_name='startup',
            index=models.Index(fields=['location', 'is_approved'], name='startups_st_locatio_5f06e2_idx'),
        ),
        migrations.AddIndex(
            model_name='startup',
            index=models.Index(fields=['created_at'], name='startups_st_created_93e688_idx'),
        ),
        migrations.AddIndex(
            model_name='startupbookmark',
            index=models.Index(fields=['user', 'created_at'], name='startups_st_user_id_92c6b9_idx'),
        ),
        migrations.AddIndex(
            model_name='startupcomment',
            index=models.Index(fields=['startup', 'created_at'], name='startups_st_startup_6fb60b_idx'),
        ),
        migrations.AddIndex(
            model_name='startupcomment',
            index=models.Index(fields=['user', 'created_at'], name='startups_st_user_id_00fb2a_idx'),
        ),
        migrations.AddIndex(
            model_name='startuplike',
            index=models.Index(fields=['startup', 'created_at'], name='startups_st_startup_618547_idx'),
        ),
        migrations.AddIndex(
            model_name='startuprating',
            index=models.Index(fields=['startup', 'created_at'], name='startups_st_startup_4e8f79_idx'),
        ),
        migrations.AddField(
            model_name='startupsubmission',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='startupsubmission',
            name='startup',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='startups.startup'),
        ),
        migrations.AddField(
            model_name='startupsubmission',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startup_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='startupsubmission',
            index=models.Index(fields=['status', 'submitted_at'], name='startups_st_status_594e10_idx'),
        ),
        migrations.AddIndex(
            model_name='startupsubmission',
            index=models.Index(fields=['submitted_by', 'submitted_at'], name='startups_st_submitt_ce1579_idx'),
        ),
    ]
