# Generated by Django 5.2.1 on 2025-05-24 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('startups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='startupbookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='startupcomment',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='startups.startup'),
        ),
        migrations.AddField(
            model_name='startupcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='startupfounder',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='founders', to='startups.startup'),
        ),
        migrations.AddField(
            model_name='startuplike',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='startups.startup'),
        ),
        migrations.AddField(
            model_name='startuplike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='startuprating',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='startups.startup'),
        ),
        migrations.AddField(
            model_name='startuprating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='startuptag',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='startups.startup'),
        ),
        migrations.AlterUniqueTogether(
            name='startupbookmark',
            unique_together={('startup', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='startuplike',
            unique_together={('startup', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='startuprating',
            unique_together={('startup', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='startuptag',
            unique_together={('startup', 'tag')},
        ),
    ]
